### ISSUE TITLE
Setup GitHub Actions

### ISSUE THREAD

**Issue by szabgab** [SBECK-github/Date-Manip#45]
I am using the [CPAN Digger](https://cpan-digger.perlmaven.com/) to locate recently release modules that don't have a working CI system. As I can see [all of your modules](https://cpan-digger.perlmaven.com/author/SBECK) that has a link to their VCS have Travis CI which unfortunately has stopped providing free service.

If you are interested I'd be happy to send you PR to this and to your other CPAN modules configuring Github Actions.

**Comment by SBECK-github** [comment]
Yes, I added Travis to all of my modules because at the time, it was fairly convenient.  I'll remove them from future releases since it hasn't been functional for a while.

I'm curious what other thing are doable in Github actions that might benefit my modules.  If you have the info written up, please send it to me and I'll certainly take a look at it.

Thanks

**Comment by szabgab** [comment]
Basically you can run any program on GitHub Actions. So you can do whatever you like.
